language: python

python:
  - "2.7"
  - "3.4"

before_install:
  # download miniconda (for Python 2 or Python 3)
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  # install miniconda
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  # update conda package manager
  - conda update --yes conda
  # create virtual environment
  - conda create -n testenv --yes --file requirements.txt python=$TRAVIS_PYTHON_VERSION
  # activate environment
  - source activate testenv
  # install test tools
  - conda install --yes pytest
  - pip install pytest-cov
  - pip install coveralls
  # debugging info
  - echo $PATH
  - which python
  - which pip
  - which py.test
  - python --version
  - conda info
  - conda list

install:
  # install package
  - python setup.py install

script: 
  - py.test

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.4" ]]; then coveralls; fi
